In [1]:
import pandas as pd
import numpy as np

In [2]:
arr=np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
s1=[1,2,3,4,5]
s2=[6,7,8,9,10]

df=pd.DataFrame([s1,s2])
print(df)
merged_df=np.add(s1,s2)
print(merged_df)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
[ 7  9 11 13 15]


In [ ]:
n=int(input("Enter a number: "))
fact=1

for i in range(1,n+1):
    fact*=i

print(f"The factorial of {n} is {fact}")

The factorial of 45 is 119622220865480194561963161495657715064383733760000000000


In [7]:
num=int(input("Enter a number: "))

if num<2:
    print("not prime")
else:
    for i in range(2,num):
        if num%i==0:
            print("not prime")
            break
    else:
        print("Prime")

Prime


In [10]:
data={'age':[32,36,36,5]}
df=pd.DataFrame(data)
print(df.sort_values(by='age',ascending=True))

   age
3    5
0   32
1   36
2   36


In [ ]:
arr=np.array([5,10,15,202,5])

print("Sum:",np.sum(arr))
print("mean:",np.mean(arr))
print("Min:",np.min(arr))
print("MAx:",np.max(arr))


Sum: 237
mean: 47.4
Min: 5
MAx: 202


In [14]:
df=pd.Series([10,30,24,20,45])
print(df[df>25])

1    30
4    45
dtype: int64


In [47]:
data={'name':['aice','bob','chgarlie'],
      'maths':[80,90,70],
      'english':[85,95,75],
      'science':[90,80,85]}

df=pd.DataFrame(data)

df['total_marks']=df[['maths','english','science']].sum(axis=1)
df['average_marks']=df[['maths','english','science']].mean(axis=1)

df

,name,maths,english,science,total_marks,average_marks
0,aice,80,85,90,255,85.000000
1,bob,90,95,80,265,88.333333
2,chgarlie,70,75,85,230,76.666667


In [29]:
data={'grade':['A','B','C','A'],
      'marks':[45,56,32,67]}

df=pd.DataFrame(data)
gb=df.groupby("grade")
print(gb)
print(gb['marks'].mean())

grade
A    56.0
B    56.0
C    32.0
Name: marks, dtype: float64


In [32]:
df=pd.Series([1,2,3,6,7,89,11,12])
print(df[df%3==0])


2     3
3     6
7    12
dtype: int64


In [33]:
arr=np.array([1,2,3,4,2,1])

uniqu_el=np.unique_counts(arr)
print(uniqu_el)

UniqueCountsResult(values=array([1, 2, 3, 4]), counts=array([2, 2, 1, 1]))


In [34]:
arr=np.array([1,4,56,89,66])

print("index max is :",np.argmax(arr))

index max is : 3


In [43]:
arr=np.array([1,2,3,4,5,6,7,89])
arr[arr%2!=0]=-1
print(arr)

[-1  2 -1  4 -1  6 -1 -1]


In [41]:
arr=np.array([30,50,70,90,100,43,33,23,])
arr[arr>50]=0
print(arr)

[30 50  0  0  0 43 33 23]


In [46]:
arr=np.arange(1,21).reshape(4,5)
print(arr)
df=pd.Series(arr)
print(df)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


ValueError: Data must be 1-dimensional, got ndarray of shape (4, 5) instead